export const historialProductos = [
  {
    id: 0,
    productId: 0,
    dateChanged: '09-27-2022',
    previousPrice: 0,
    newPrice: 0,
    previousStock: 0,
    newStock: 0,
    previousName: 'Bicicleta',
    newName: 'Bicicleta Playera',
  },
  {
    id: 1,
    productId: 0,
    dateChanged: '09-27-2022',
    previousPrice: 100,
    newPrice: 150,
    previousStock: 0,
    newStock: 0,
    previousName: '',
    newName: '',
  },
  {
    id: 2,
    productId: 1,
    dateChanged: '09-27-2022',
    previousPrice: 0,
    newPrice: 0,
    previousStock: 1,
    newStock: 10,
    previousName: '',
    newName: '',
  },
  {
    id: 3,
    productId: 2,
    dateChanged: '09-27-2022',
    previousPrice: 120,
    newPrice: 100,
    previousStock: 0,
    newStock: 0,
    previousName: '',
    newName: '',
  },
];
