# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import auction_pb2 as auction__pb2


class auctionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.comprar = channel.unary_unary(
                '/auction/comprar',
                request_serializer=auction__pb2.RegisterAuction.SerializeToString,
                response_deserializer=auction__pb2.ResponseAuction.FromString,
                )
        self.getAuctionsByUserPurchase = channel.unary_unary(
                '/auction/getAuctionsByUserPurchase',
                request_serializer=auction__pb2.RequestUserId.SerializeToString,
                response_deserializer=auction__pb2.ListAuction.FromString,
                )


class auctionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def comprar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAuctionsByUserPurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_auctionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'comprar': grpc.unary_unary_rpc_method_handler(
                    servicer.comprar,
                    request_deserializer=auction__pb2.RegisterAuction.FromString,
                    response_serializer=auction__pb2.ResponseAuction.SerializeToString,
            ),
            'getAuctionsByUserPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.getAuctionsByUserPurchase,
                    request_deserializer=auction__pb2.RequestUserId.FromString,
                    response_serializer=auction__pb2.ListAuction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class auction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def comprar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auction/comprar',
            auction__pb2.RegisterAuction.SerializeToString,
            auction__pb2.ResponseAuction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAuctionsByUserPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auction/getAuctionsByUserPurchase',
            auction__pb2.RequestUserId.SerializeToString,
            auction__pb2.ListAuction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
