# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rauction.proto\"\x1f\n\rRequestUserId\x12\x0e\n\x06userId\x18\x01 \x01(\x03\"Q\n\x0fRegisterAuction\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x11\n\tproductId\x18\x02 \x01(\x03\x12\r\n\x05total\x18\x03 \x01(\x01\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"]\n\x0fResponseAuction\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06userId\x18\x02 \x01(\x03\x12\x11\n\tproductId\x18\x03 \x01(\x03\x12\r\n\x05total\x18\x04 \x01(\x01\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\"1\n\x0bListAuction\x12\"\n\x08\x61uctions\x18\x01 \x03(\x0b\x32\x10.ResponseAuction2s\n\x07\x61uction\x12-\n\x07\x63omprar\x12\x10.RegisterAuction\x1a\x10.ResponseAuction\x12\x39\n\x19getAuctionsByUserPurchase\x12\x0e.RequestUserId\x1a\x0c.ListAuctionB\x1d\n\x19\x63om.unla.servicegrpc.grpcP\x01\x62\x06proto3')



_REQUESTUSERID = DESCRIPTOR.message_types_by_name['RequestUserId']
_REGISTERAUCTION = DESCRIPTOR.message_types_by_name['RegisterAuction']
_RESPONSEAUCTION = DESCRIPTOR.message_types_by_name['ResponseAuction']
_LISTAUCTION = DESCRIPTOR.message_types_by_name['ListAuction']
RequestUserId = _reflection.GeneratedProtocolMessageType('RequestUserId', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTUSERID,
  '__module__' : 'auction_pb2'
  # @@protoc_insertion_point(class_scope:RequestUserId)
  })
_sym_db.RegisterMessage(RequestUserId)

RegisterAuction = _reflection.GeneratedProtocolMessageType('RegisterAuction', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERAUCTION,
  '__module__' : 'auction_pb2'
  # @@protoc_insertion_point(class_scope:RegisterAuction)
  })
_sym_db.RegisterMessage(RegisterAuction)

ResponseAuction = _reflection.GeneratedProtocolMessageType('ResponseAuction', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEAUCTION,
  '__module__' : 'auction_pb2'
  # @@protoc_insertion_point(class_scope:ResponseAuction)
  })
_sym_db.RegisterMessage(ResponseAuction)

ListAuction = _reflection.GeneratedProtocolMessageType('ListAuction', (_message.Message,), {
  'DESCRIPTOR' : _LISTAUCTION,
  '__module__' : 'auction_pb2'
  # @@protoc_insertion_point(class_scope:ListAuction)
  })
_sym_db.RegisterMessage(ListAuction)

_AUCTION = DESCRIPTOR.services_by_name['auction']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.unla.servicegrpc.grpcP\001'
  _REQUESTUSERID._serialized_start=17
  _REQUESTUSERID._serialized_end=48
  _REGISTERAUCTION._serialized_start=50
  _REGISTERAUCTION._serialized_end=131
  _RESPONSEAUCTION._serialized_start=133
  _RESPONSEAUCTION._serialized_end=226
  _LISTAUCTION._serialized_start=228
  _LISTAUCTION._serialized_end=277
  _AUCTION._serialized_start=279
  _AUCTION._serialized_end=394
# @@protoc_insertion_point(module_scope)
