# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinvoice.proto\"\x1a\n\x07\x62uyerId\x12\x0f\n\x07\x62uyerId\x18\x01 \x01(\x03\"/\n\x0bgetInvoices\x12 \n\x08invoices\x18\x01 \x03(\x0b\x32\x0e.invoiceObject\"\x92\x01\n\rinvoiceObject\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x17\n\x06seller\x18\x03 \x01(\x0b\x32\x07.seller\x12\x15\n\x05\x62uyer\x18\x04 \x01(\x0b\x32\x06.buyer\x12(\n\x08products\x18\x05 \x03(\x0b\x32\x16.invoiceProductObjects\x12\r\n\x05total\x18\x06 \x01(\x01\"I\n\x06seller\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"H\n\x05\x62uyer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"F\n\x15invoiceProductObjects\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x32\x31\n\x07invoice\x12&\n\x0clistInvoices\x12\x08.buyerId\x1a\x0c.getInvoicesB\x1d\n\x19\x63om.unla.servicegrpc.grpcP\x01\x62\x06proto3')



_BUYERID = DESCRIPTOR.message_types_by_name['buyerId']
_GETINVOICES = DESCRIPTOR.message_types_by_name['getInvoices']
_INVOICEOBJECT = DESCRIPTOR.message_types_by_name['invoiceObject']
_SELLER = DESCRIPTOR.message_types_by_name['seller']
_BUYER = DESCRIPTOR.message_types_by_name['buyer']
_INVOICEPRODUCTOBJECTS = DESCRIPTOR.message_types_by_name['invoiceProductObjects']
buyerId = _reflection.GeneratedProtocolMessageType('buyerId', (_message.Message,), {
  'DESCRIPTOR' : _BUYERID,
  '__module__' : 'invoice_pb2'
  # @@protoc_insertion_point(class_scope:buyerId)
  })
_sym_db.RegisterMessage(buyerId)

getInvoices = _reflection.GeneratedProtocolMessageType('getInvoices', (_message.Message,), {
  'DESCRIPTOR' : _GETINVOICES,
  '__module__' : 'invoice_pb2'
  # @@protoc_insertion_point(class_scope:getInvoices)
  })
_sym_db.RegisterMessage(getInvoices)

invoiceObject = _reflection.GeneratedProtocolMessageType('invoiceObject', (_message.Message,), {
  'DESCRIPTOR' : _INVOICEOBJECT,
  '__module__' : 'invoice_pb2'
  # @@protoc_insertion_point(class_scope:invoiceObject)
  })
_sym_db.RegisterMessage(invoiceObject)

seller = _reflection.GeneratedProtocolMessageType('seller', (_message.Message,), {
  'DESCRIPTOR' : _SELLER,
  '__module__' : 'invoice_pb2'
  # @@protoc_insertion_point(class_scope:seller)
  })
_sym_db.RegisterMessage(seller)

buyer = _reflection.GeneratedProtocolMessageType('buyer', (_message.Message,), {
  'DESCRIPTOR' : _BUYER,
  '__module__' : 'invoice_pb2'
  # @@protoc_insertion_point(class_scope:buyer)
  })
_sym_db.RegisterMessage(buyer)

invoiceProductObjects = _reflection.GeneratedProtocolMessageType('invoiceProductObjects', (_message.Message,), {
  'DESCRIPTOR' : _INVOICEPRODUCTOBJECTS,
  '__module__' : 'invoice_pb2'
  # @@protoc_insertion_point(class_scope:invoiceProductObjects)
  })
_sym_db.RegisterMessage(invoiceProductObjects)

_INVOICE = DESCRIPTOR.services_by_name['invoice']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.unla.servicegrpc.grpcP\001'
  _BUYERID._serialized_start=17
  _BUYERID._serialized_end=43
  _GETINVOICES._serialized_start=45
  _GETINVOICES._serialized_end=92
  _INVOICEOBJECT._serialized_start=95
  _INVOICEOBJECT._serialized_end=241
  _SELLER._serialized_start=243
  _SELLER._serialized_end=316
  _BUYER._serialized_start=318
  _BUYER._serialized_end=390
  _INVOICEPRODUCTOBJECTS._serialized_start=392
  _INVOICEPRODUCTOBJECTS._serialized_end=462
  _INVOICE._serialized_start=464
  _INVOICE._serialized_end=513
# @@protoc_insertion_point(module_scope)
