# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"d\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"_\n\x10RegisterResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x10\n\x08username\x18\x05 \x01(\t\"\x15\n\x07GetById\x12\n\n\x02id\x18\x01 \x01(\x03\x32[\n\x04user\x12/\n\x08register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12\"\n\x03get\x12\x08.GetById\x1a\x11.RegisterResponseB\x1d\n\x19\x63om.unla.servicegrpc.grpcP\x01\x62\x06proto3')



_REGISTERREQUEST = DESCRIPTOR.message_types_by_name['RegisterRequest']
_REGISTERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterResponse']
_GETBYID = DESCRIPTOR.message_types_by_name['GetById']
RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

GetById = _reflection.GeneratedProtocolMessageType('GetById', (_message.Message,), {
  'DESCRIPTOR' : _GETBYID,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:GetById)
  })
_sym_db.RegisterMessage(GetById)

_USER = DESCRIPTOR.services_by_name['user']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.unla.servicegrpc.grpcP\001'
  _REGISTERREQUEST._serialized_start=14
  _REGISTERREQUEST._serialized_end=114
  _REGISTERRESPONSE._serialized_start=116
  _REGISTERRESPONSE._serialized_end=211
  _GETBYID._serialized_start=213
  _GETBYID._serialized_end=234
  _USER._serialized_start=236
  _USER._serialized_end=327
# @@protoc_insertion_point(module_scope)
