# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x07\n\x05\x45mpty\"r\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\"m\n\x10RegisterResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x10\n\x08username\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\"\x15\n\x07GetById\x12\n\n\x02id\x18\x01 \x01(\x03\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\";\n\rLoginResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"!\n\x0eLogoutResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa6\x01\n\x04user\x12/\n\x08register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12\"\n\x03get\x12\x08.GetById\x1a\x11.RegisterResponse\x12&\n\x05login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12!\n\x06logout\x12\x06.Empty\x1a\x0f.LogoutResponseB\x1d\n\x19\x63om.unla.servicegrpc.grpcP\x01\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_REGISTERREQUEST = DESCRIPTOR.message_types_by_name['RegisterRequest']
_REGISTERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterResponse']
_GETBYID = DESCRIPTOR.message_types_by_name['GetById']
_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_LOGOUTRESPONSE = DESCRIPTOR.message_types_by_name['LogoutResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

GetById = _reflection.GeneratedProtocolMessageType('GetById', (_message.Message,), {
  'DESCRIPTOR' : _GETBYID,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:GetById)
  })
_sym_db.RegisterMessage(GetById)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

LogoutResponse = _reflection.GeneratedProtocolMessageType('LogoutResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUTRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:LogoutResponse)
  })
_sym_db.RegisterMessage(LogoutResponse)

_USER = DESCRIPTOR.services_by_name['user']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.unla.servicegrpc.grpcP\001'
  _EMPTY._serialized_start=14
  _EMPTY._serialized_end=21
  _REGISTERREQUEST._serialized_start=23
  _REGISTERREQUEST._serialized_end=137
  _REGISTERRESPONSE._serialized_start=139
  _REGISTERRESPONSE._serialized_end=248
  _GETBYID._serialized_start=250
  _GETBYID._serialized_end=271
  _LOGINREQUEST._serialized_start=273
  _LOGINREQUEST._serialized_end=323
  _LOGINRESPONSE._serialized_start=325
  _LOGINRESPONSE._serialized_end=384
  _LOGOUTRESPONSE._serialized_start=386
  _LOGOUTRESPONSE._serialized_end=419
  _USER._serialized_start=422
  _USER._serialized_end=588
# @@protoc_insertion_point(module_scope)
