# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wallet_pb2 as wallet__pb2


class walletStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/wallet/add',
                request_serializer=wallet__pb2.RegisterRequestWallet.SerializeToString,
                response_deserializer=wallet__pb2.RegisterResponseWallet.FromString,
                )
        self.subtract = channel.unary_unary(
                '/wallet/subtract',
                request_serializer=wallet__pb2.RegisterRequestWallet.SerializeToString,
                response_deserializer=wallet__pb2.ResponseAPIWallet.FromString,
                )


class walletServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_walletServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=wallet__pb2.RegisterRequestWallet.FromString,
                    response_serializer=wallet__pb2.RegisterResponseWallet.SerializeToString,
            ),
            'subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.subtract,
                    request_deserializer=wallet__pb2.RegisterRequestWallet.FromString,
                    response_serializer=wallet__pb2.ResponseAPIWallet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class wallet(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wallet/add',
            wallet__pb2.RegisterRequestWallet.SerializeToString,
            wallet__pb2.RegisterResponseWallet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wallet/subtract',
            wallet__pb2.RegisterRequestWallet.SerializeToString,
            wallet__pb2.ResponseAPIWallet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
